name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/setup-node@v3
        with:
          node-version: 18.1.0
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          # Creates a local build for the dev server
          build: npm run build
          # Starts a local server for tests
          start: npm start
